package net.sigusr

import org.scalatest.funsuite.AnyFunSuite
import io.circe.parser._

class CodecsTest extends AnyFunSuite {

  test("A correct Json body should deserialize to a list of Repo") {
    import net.sigusr.Codecs._
    val sourceJson =
      """
[
  {
    "id": 71716090,
    "node_id": "MDEwOlJlcG9zaXRvcnk3MTcxNjA5MA==",
    "name": "Acteurs",
    "full_name": "fcabestre/Acteurs",
    "private": false,
    "owner": {
      "login": "fcabestre",
      "id": 912629,
      "node_id": "MDQ6VXNlcjkxMjYyOQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/912629?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fcabestre",
      "html_url": "https://github.com/fcabestre",
      "followers_url": "https://api.github.com/users/fcabestre/followers",
      "following_url": "https://api.github.com/users/fcabestre/following{/other_user}",
      "gists_url": "https://api.github.com/users/fcabestre/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fcabestre/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fcabestre/subscriptions",
      "organizations_url": "https://api.github.com/users/fcabestre/orgs",
      "repos_url": "https://api.github.com/users/fcabestre/repos",
      "events_url": "https://api.github.com/users/fcabestre/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fcabestre/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/fcabestre/Acteurs",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/fcabestre/Acteurs",
    "forks_url": "https://api.github.com/repos/fcabestre/Acteurs/forks",
    "keys_url": "https://api.github.com/repos/fcabestre/Acteurs/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/fcabestre/Acteurs/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/fcabestre/Acteurs/teams",
    "hooks_url": "https://api.github.com/repos/fcabestre/Acteurs/hooks",
    "issue_events_url": "https://api.github.com/repos/fcabestre/Acteurs/issues/events{/number}",
    "events_url": "https://api.github.com/repos/fcabestre/Acteurs/events",
    "assignees_url": "https://api.github.com/repos/fcabestre/Acteurs/assignees{/user}",
    "branches_url": "https://api.github.com/repos/fcabestre/Acteurs/branches{/branch}",
    "tags_url": "https://api.github.com/repos/fcabestre/Acteurs/tags",
    "blobs_url": "https://api.github.com/repos/fcabestre/Acteurs/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/fcabestre/Acteurs/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/fcabestre/Acteurs/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/fcabestre/Acteurs/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/fcabestre/Acteurs/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/fcabestre/Acteurs/languages",
    "stargazers_url": "https://api.github.com/repos/fcabestre/Acteurs/stargazers",
    "contributors_url": "https://api.github.com/repos/fcabestre/Acteurs/contributors",
    "subscribers_url": "https://api.github.com/repos/fcabestre/Acteurs/subscribers",
    "subscription_url": "https://api.github.com/repos/fcabestre/Acteurs/subscription",
    "commits_url": "https://api.github.com/repos/fcabestre/Acteurs/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/fcabestre/Acteurs/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/fcabestre/Acteurs/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/fcabestre/Acteurs/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/fcabestre/Acteurs/contents/{+path}",
    "compare_url": "https://api.github.com/repos/fcabestre/Acteurs/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/fcabestre/Acteurs/merges",
    "archive_url": "https://api.github.com/repos/fcabestre/Acteurs/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/fcabestre/Acteurs/downloads",
    "issues_url": "https://api.github.com/repos/fcabestre/Acteurs/issues{/number}",
    "pulls_url": "https://api.github.com/repos/fcabestre/Acteurs/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/fcabestre/Acteurs/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/fcabestre/Acteurs/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/fcabestre/Acteurs/labels{/name}",
    "releases_url": "https://api.github.com/repos/fcabestre/Acteurs/releases{/id}",
    "deployments_url": "https://api.github.com/repos/fcabestre/Acteurs/deployments",
    "created_at": "2016-10-23T16:48:04Z",
    "updated_at": "2017-03-25T10:13:36Z",
    "pushed_at": "2017-03-25T09:56:00Z",
    "git_url": "git://github.com/fcabestre/Acteurs.git",
    "ssh_url": "git@github.com:fcabestre/Acteurs.git",
    "clone_url": "https://github.com/fcabestre/Acteurs.git",
    "svn_url": "https://github.com/fcabestre/Acteurs",
    "homepage": null,
    "size": 64831,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 150954733,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNTA5NTQ3MzM=",
    "name": "Application-Android-24h-du-Mans",
    "full_name": "fcabestre/Application-Android-24h-du-Mans",
    "private": false,
    "owner": {
      "login": "fcabestre",
      "id": 912629,
      "node_id": "MDQ6VXNlcjkxMjYyOQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/912629?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fcabestre",
      "html_url": "https://github.com/fcabestre",
      "followers_url": "https://api.github.com/users/fcabestre/followers",
      "following_url": "https://api.github.com/users/fcabestre/following{/other_user}",
      "gists_url": "https://api.github.com/users/fcabestre/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fcabestre/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fcabestre/subscriptions",
      "organizations_url": "https://api.github.com/users/fcabestre/orgs",
      "repos_url": "https://api.github.com/users/fcabestre/repos",
      "events_url": "https://api.github.com/users/fcabestre/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fcabestre/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/fcabestre/Application-Android-24h-du-Mans",
    "description": "Version 0.7.2",
    "fork": true,
    "url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans",
    "forks_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/forks",
    "keys_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/teams",
    "hooks_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/hooks",
    "issue_events_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/issues/events{/number}",
    "events_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/events",
    "assignees_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/assignees{/user}",
    "branches_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/branches{/branch}",
    "tags_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/tags",
    "blobs_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/languages",
    "stargazers_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/stargazers",
    "contributors_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/contributors",
    "subscribers_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/subscribers",
    "subscription_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/subscription",
    "commits_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/contents/{+path}",
    "compare_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/merges",
    "archive_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/downloads",
    "issues_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/issues{/number}",
    "pulls_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/labels{/name}",
    "releases_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/releases{/id}",
    "deployments_url": "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/deployments",
    "created_at": "2018-09-30T09:54:21Z",
    "updated_at": "2018-11-28T18:29:33Z",
    "pushed_at": "2018-11-28T18:29:32Z",
    "git_url": "git://github.com/fcabestre/Application-Android-24h-du-Mans.git",
    "ssh_url": "git@github.com:fcabestre/Application-Android-24h-du-Mans.git",
    "clone_url": "https://github.com/fcabestre/Application-Android-24h-du-Mans.git",
    "svn_url": "https://github.com/fcabestre/Application-Android-24h-du-Mans",
    "homepage": null,
    "size": 201,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 73107689,
    "node_id": "MDEwOlJlcG9zaXRvcnk3MzEwNzY4OQ==",
    "name": "BBL-TLS",
    "full_name": "fcabestre/BBL-TLS",
    "private": false,
    "owner": {
      "login": "fcabestre",
      "id": 912629,
      "node_id": "MDQ6VXNlcjkxMjYyOQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/912629?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fcabestre",
      "html_url": "https://github.com/fcabestre",
      "followers_url": "https://api.github.com/users/fcabestre/followers",
      "following_url": "https://api.github.com/users/fcabestre/following{/other_user}",
      "gists_url": "https://api.github.com/users/fcabestre/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fcabestre/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fcabestre/subscriptions",
      "organizations_url": "https://api.github.com/users/fcabestre/orgs",
      "repos_url": "https://api.github.com/users/fcabestre/repos",
      "events_url": "https://api.github.com/users/fcabestre/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fcabestre/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/fcabestre/BBL-TLS",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/fcabestre/BBL-TLS",
    "forks_url": "https://api.github.com/repos/fcabestre/BBL-TLS/forks",
    "keys_url": "https://api.github.com/repos/fcabestre/BBL-TLS/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/fcabestre/BBL-TLS/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/fcabestre/BBL-TLS/teams",
    "hooks_url": "https://api.github.com/repos/fcabestre/BBL-TLS/hooks",
    "issue_events_url": "https://api.github.com/repos/fcabestre/BBL-TLS/issues/events{/number}",
    "events_url": "https://api.github.com/repos/fcabestre/BBL-TLS/events",
    "assignees_url": "https://api.github.com/repos/fcabestre/BBL-TLS/assignees{/user}",
    "branches_url": "https://api.github.com/repos/fcabestre/BBL-TLS/branches{/branch}",
    "tags_url": "https://api.github.com/repos/fcabestre/BBL-TLS/tags",
    "blobs_url": "https://api.github.com/repos/fcabestre/BBL-TLS/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/fcabestre/BBL-TLS/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/fcabestre/BBL-TLS/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/fcabestre/BBL-TLS/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/fcabestre/BBL-TLS/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/fcabestre/BBL-TLS/languages",
    "stargazers_url": "https://api.github.com/repos/fcabestre/BBL-TLS/stargazers",
    "contributors_url": "https://api.github.com/repos/fcabestre/BBL-TLS/contributors",
    "subscribers_url": "https://api.github.com/repos/fcabestre/BBL-TLS/subscribers",
    "subscription_url": "https://api.github.com/repos/fcabestre/BBL-TLS/subscription",
    "commits_url": "https://api.github.com/repos/fcabestre/BBL-TLS/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/fcabestre/BBL-TLS/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/fcabestre/BBL-TLS/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/fcabestre/BBL-TLS/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/fcabestre/BBL-TLS/contents/{+path}",
    "compare_url": "https://api.github.com/repos/fcabestre/BBL-TLS/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/fcabestre/BBL-TLS/merges",
    "archive_url": "https://api.github.com/repos/fcabestre/BBL-TLS/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/fcabestre/BBL-TLS/downloads",
    "issues_url": "https://api.github.com/repos/fcabestre/BBL-TLS/issues{/number}",
    "pulls_url": "https://api.github.com/repos/fcabestre/BBL-TLS/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/fcabestre/BBL-TLS/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/fcabestre/BBL-TLS/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/fcabestre/BBL-TLS/labels{/name}",
    "releases_url": "https://api.github.com/repos/fcabestre/BBL-TLS/releases{/id}",
    "deployments_url": "https://api.github.com/repos/fcabestre/BBL-TLS/deployments",
    "created_at": "2016-11-07T18:20:39Z",
    "updated_at": "2016-11-07T18:21:20Z",
    "pushed_at": "2016-11-07T18:21:18Z",
    "git_url": "git://github.com/fcabestre/BBL-TLS.git",
    "ssh_url": "git@github.com:fcabestre/BBL-TLS.git",
    "clone_url": "https://github.com/fcabestre/BBL-TLS.git",
    "svn_url": "https://github.com/fcabestre/BBL-TLS",
    "homepage": null,
    "size": 1871,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  }
]
    """
    val expected = List(
      Repository(
        "Acteurs",
        "https://api.github.com/repos/fcabestre/Acteurs/languages",
        "https://api.github.com/repos/fcabestre/Acteurs/contributors"
      ),
      Repository(
        "Application-Android-24h-du-Mans",
        "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/languages",
        "https://api.github.com/repos/fcabestre/Application-Android-24h-du-Mans/contributors"
      ),
      Repository(
        "BBL-TLS",
        "https://api.github.com/repos/fcabestre/BBL-TLS/languages",
        "https://api.github.com/repos/fcabestre/BBL-TLS/contributors"
      ))

    parse(sourceJson).fold(
      f => fail(f.getMessage()),
      _.as[List[Repository]].fold(
        f => fail(f.getMessage()),
        f => assert(f == expected)))
  }

  test("A correct Json body should deserialize to a list of Contributor") {
    import net.sigusr.Codecs._
    val sourceJson =
      """
[
    {
        "avatar_url": "https://avatars3.githubusercontent.com/u/912629?v=4",
        "contributions": 15,
        "events_url": "https://api.github.com/users/fcabestre/events{/privacy}",
        "followers_url": "https://api.github.com/users/fcabestre/followers",
        "following_url": "https://api.github.com/users/fcabestre/following{/other_user}",
        "gists_url": "https://api.github.com/users/fcabestre/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/fcabestre",
        "id": 912629,
        "login": "fcabestre",
        "node_id": "MDQ6VXNlcjkxMjYyOQ==",
        "organizations_url": "https://api.github.com/users/fcabestre/orgs",
        "received_events_url": "https://api.github.com/users/fcabestre/received_events",
        "repos_url": "https://api.github.com/users/fcabestre/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/fcabestre/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/fcabestre/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/fcabestre"
    }
]
      """

    val expected = List(Contributor("fcabestre"))

    parse(sourceJson).fold(
      f => fail(f.getMessage()),
      _.as[List[Contributor]].fold(
        f => fail(f.getMessage()),
        f => assert(f == expected)))

  }
}

